### ISSUE TITLE
Incompatible with JDK 13

### ISSUE THREAD

**Issue by kuon** [orchidhq/Orchid#356]
Because of a pebble issue, Orchid is not compatible with JDK 13.

It has been fixed in pebble 3.1.2 so bumping the version should fix the issue.

For reference: https://github.com/PebbleTemplates/pebble/issues/487

**Comment by cjbrooks12** [comment]
Good to know, thanks for the tip. I'll get that bumped in the next version, which should be coming out in the next few days. I'll look into getting CI tests for JDK 13 too, to make sure nothing else is broken.

**Comment by cjbrooks12** [comment]
This has been fixed in 0.19.0. The rest of Orchid seems to be working fine, too, except for the Javadoc plugin, due to the Javadoc APIs being moved to a different module and package in JDK9, and the old APIs having been removed in JDK12. This will take some additional work to get the Javadoc plugin functional in JDK12+, unfortunately, but the rest of Orchid is working great under JDK13.
