### ISSUE TITLE
Doesn't work with maven? 

### ISSUE THREAD

**Issue by KingZee** [orchidhq/Orchid#360]
I'm getting a : 
```
Errors:
EditorialTheme: 
    - Editorial Theme configuration of search has been removed, and you must now migrate to the `orchidSearch` or `algoliaDocsearch` meta-component config instead.
```
after running build goal. What is the problem?

**Comment by cjbrooks12** [comment]
Since Orchid _is_ running, the Maven integration is working fine (it's just a lightweight CLI wrapper). 

That error just notices that a deprecated feature has been removed and replaced with a different feature, likely breaking older sites using that feature if they have no migrated already. You can safely ignore it, and the following snippet in your `config.yml` will hide the message:

```yml
theme:
  legacySearch: false
```
